<div class="container my-3">
    <div class="row">
        <div class="col-12">
            <a href="<?= $this->url('vehicles') ?>" class="btn btn-primary mb-3">
                <i class="fa fa-arrow-left"></i> Voltar
            </a>
        </div>
    </div>
    <div class="row py-3">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h2 class="m-0">Adicionar Veículo</h2>
                </div>
                <div class="card-body">
                    <form action="<?= $this->url('vehicles', ['action' => 'add']) ?>" method="post" id="formCadastro">
                        <div class="form-group row">
                            <div class="col-auto py-2">
                                <label for="id">Id:</label>
                                <input type="number" class="form-control" id="id" name="id"
                                       required>
                            </div>
                            <div class="col-auto py-2">
                                <label for="placa">Placa:</label>
                                <input type="text" class="form-control" id="placa" name="placa"

                                       required
                                       maxlength="7">
                            </div>
                            <div class="col-auto py-2">
                                <label for="renavam">Renavam:</label>
                                <input type="text" class="form-control" id="renavam" name="renavam" maxlength="30">
                            </div>
                            <div class="col-auto py-2">
                                <label for="modelo">Modelo:</label>
                                <input type="text" class="form-control" id="modelo" name="modelo" required
                                       maxlength="20">
                            </div>
                            <div class="col-auto py-2">
                                <label for="marca">Marca:</label>
                                <input type="text" class="form-control" id="marca" name="marca" required maxlength="20">
                            </div>
                            <div class="col-auto py-2">
                                <label for="ano">Ano:</label>
                                <input type="number" class="form-control" id="ano" name="ano" required>
                            </div>
                            <div class="col-auto py-2">
                                <label for="cor">Cor:</label>
                                <input type="text" class="form-control" id="cor" name="cor" required maxlength="20">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success" id="addButton" disabled>Adicionar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
$flashMessenger = $this->flashMessenger();
if ($flashMessenger->hasSuccessMessages()) {
    $successMessage = $flashMessenger->getSuccessMessages()[0];
    echo '<div class="alert alert-success">1' . $this->escapeHtml($successMessage) . '</div>';
}
?>

<script>
    const form = document.getElementById('formCadastro');
    const submitButton = document.getElementById('addButton');

    form.addEventListener('input', function() {
        const inputs = form.querySelectorAll('input[required]');
        let allValid = true;

        inputs.forEach(input => {
            if (!input.value) {
                allValid = false;
            }
        });

        submitButton.disabled = !allValid;
    });
</script>
