<div class="container my-3">
    <div class="row">
        <div class="col-12">
            <a href="<?= $this->url('motorists') ?>" class="btn btn-primary mb-3">
                <i class="fa fa-arrow-left"></i> Voltar
            </a>
        </div>
    </div>
    <div class="row py-3">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h2 class="m-0">Adicionar Motorista</h2>
                </div>
                <div class="card-body">
                    <form action="<?= $this->url('motorists', ['action' => 'add']) ?>" method="post" id="formCadastro">
                        <div class="form-group row">
                            <div class="col-auto py-2">
                                <label for="nome">Nome:</label>
                                <input type="text" class="form-control" id="nome" name="nome" required maxlength="200">
                            </div>
                            <div class="col-auto py-2">
                                <label for="rg">RG:</label>
                                <input type="text" class="form-control rg" id="rg" name="rg" maxlength="20" required>
                            </div>
                            <div class="col-auto py-2">
                                <label for="cpf">CPF:</label>
                                <input type="text" class="form-control cpf" id="cpf" name="cpf" maxlength="15" required>
                            </div>
                            <div class="col-auto py-2">
                                <label for="telefone">Telefone:</label>
                                <input type="text" class="form-control telefone" id="telefone" name="telefone"
                                       maxlength="20">
                            </div>
                            <div class="col-auto py-2">
                                <label for="vehicle_id">Veiculo:</label>
                                <select class="form-control" id="vehicle_id" name="vehicle_id">
                                    <option value="null">Selecione</option>
                                    <?php foreach ($vehicles as $vehicle): ?>
                                        <option value="<?= $vehicle->getId() ?>"><?= $vehicle->getPlaca() ?>
                                            • <?= $vehicle->getModelo() ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success" id="saveButton" disabled>Adicionar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
