<div class="container">
    <div class="row py-3">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h2 class="card-title m-0">Lista de Motoristas</h2>
                    <a href="<?= $this->url('motorists', ['action' => 'add']); ?>"
                       class="btn btn-primary">
                        Novo Motorista <i class="fa fa-plus"></i>
                    </a>
                </div>
                <div class="card-body">
                    <table class="table table-hover table-striped" id="dtExclusive">
                        <thead>
                        <tr>
                            <th>Nome</th>
                            <th>RG</th>
                            <th>CPF</th>
                            <th>Telefone</th>
                            <th>Veiculo</th>
                            <th>Ações</th>
                        </tr>
                        </thead>
                        <tbody>
                        <!-- Loop para exibir os motoristas -->
                        <?php foreach ($this->motorists as $motorist) : ?>
                            <tr>
                                <td><?= $motorist->getNome(); ?></td>
                                <td class="rg"><?= $motorist->getRg(); ?></td>
                                <td class="cpf"><?= $motorist->getCpf(); ?></td>
                                <td class="telefone"><?= $motorist->getTelefone(); ?></td>
                                <?php if ($motorist->getVehicleId() == 0) : ?>
                                    <td>Nenhum</td>
                                <?php else: ?>
                                    <?php foreach ($this->vehicles as $vehicle) : ?>
                                        <?php if ($vehicle->getId() == $motorist->getVehicleId()) : ?>
                                            <td><?= $vehicle->getPlaca() ?> • <?= $vehicle->getModelo() ?></td>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                                <td>
                                    <a href="<?= $this->url('motorists', ['action' => 'edit', 'id' => $motorist->getId()]); ?>"
                                       class="btn btn-sm btn-warning">Editar</a>
                                    <a href="<?= $this->url('motorists', ['action' => 'delete', 'id' => $motorist->getId()]); ?>"
                                       class="btn btn-sm btn-danger">Excluir</a>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
