<div class="container my-3">
    <div class="row">
        <div class="col-12">
            <a href="<?= $this->url('motorists') ?>" class="btn btn-primary mb-3">
                <i class="fa fa-arrow-left"></i> Voltar
            </a>
        </div>
    </div>
    <div class="row py-3">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h2 class="m-0">Editar Motorista</h2>
                    <div>
                        <a href="<?= $this->url('motorists', ['action' => 'edit', 'id' => $motorist->getId()]); ?>"
                           class="btn btn-warning">
                            Editar Motorista <i class="fa fa-pencil"></i>
                        </a>
                        <a href="<?= $this->url('motorists', ['action' => 'delete']); ?>"
                           class="btn btn-danger">
                            Excluir Motorista <i class="fa fa-trash"></i>
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <form>
                        <div class="form-group row">
                            <div class="col-auto py-2">
                                <label for="placa">Nome</label>
                                <input disabled type="text" class="form-control" id="nome" name="nome"
                                       value="<?= $motorist->getNome() ?>"
                                       required
                                       maxlength="200">
                            </div>
                            <div class="col-auto py-2">
                                <label for="rg">RG:</label>
                                <input disabled type="text" class="form-control rg" id="rg" name="rg"
                                       value="<?= $motorist->getRg() ?>"
                                       maxlength="20" required>
                            </div>
                            <div class="col-auto py-2">
                                <label for="cpf">CPF:</label>
                                <input disabled type="text" class="form-control cpf" id="cpf" name="cpf"
                                       value="<?= $motorist->getCpf() ?>"
                                       maxlength="15" required>
                            </div>
                            <div class="col-auto py-2">
                                <label for="telefone">Telefone:</label>
                                <input disabled type="text" class="form-control telefone" id="telefone" name="telefone"
                                       value="<?= $motorist->getTelefone() ?>"
                                       maxlength="20">
                            </div>
                            <div class="col-auto py-2">
                                <label for="vehicle_id">Veiculo:</label>
                                <select disabled class="form-control" id="vehicle_id" name="vehicle_id">
                                    <option value="">Selecione</option>
                                    <?php foreach ($vehicles as $vehicle): ?>
                                        <option value="<?= $vehicle->getId() ?>"
                                            <?= $vehicle->getId() == $motorist->getVehicleId() ? 'selected' : '' ?>>
                                            <?= $vehicle->getPlaca() ?> • <?= $vehicle->getModelo() ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
$flashMessenger = $this->flashMessenger();
if ($flashMessenger->hasSuccessMessages()) {
    $successMessage = $flashMessenger->getSuccessMessages()[0];
    echo '<div class="alert alert-success">' . $this->escapeHtml($successMessage) . '</div>';
}
?>
