<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Sistema de Logística</title>
    <?= $this->headTitle('ZF Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/dataTables.min.css'))
    ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <!-- Scripts -->
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
    ?>
</head>
<body>
<?= $this->inlineScript()
    ->prependFile($this->basePath('js/jquery-dataTables.min.js'))
    ->prependFile($this->basePath('js/jquery.mask.min.js'))
    ->prependFile($this->basePath('js/custom/main.js'))
?>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28"
                     alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Gerenciamento de Frota
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link <?= $this->url('home') === $_SERVER['REQUEST_URI'] ? 'active' : '' ?>"
                       href="<?= $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link <?= $this->url('vehicles') === $_SERVER['REQUEST_URI'] ? 'active' : '' ?>"
                       href="<?= $this->url('vehicles') ?>">Veículos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link <?= $this->url('motorists') === $_SERVER['REQUEST_URI'] ? 'active' : '' ?>"
                       href="<?= $this->url('motorists') ?>">Motoristas</a>
                </li>
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link --><?php //= $this->url('vehicles') === $_SERVER['REQUEST_URI'] ? 'active' : '' ?><!--"-->
<!--                       href="--><?php //= $this->url('vehicles') ?><!--">Rastreio</a>-->
<!--                </li>-->
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?= $this->content ?>
    <hr>
    <footer>
        <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
    </footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
