<div class="container my-3">
    <div class="row">
        <div class="col-12">
            <a href="<?= $this->url('vehicles') ?>" class="btn btn-primary mb-3">
                <i class="fa fa-arrow-left"></i> Voltar
            </a>
        </div>
    </div>
    <div class="row py-3">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h2 class="m-0">Editar Veículo</h2>
                    <a href="<?= $this->url('vehicles', ['action' => 'delete', 'id' => $vehicle->getId()]); ?>"
                       class="btn btn-danger">
                        Excluir Veículo <i class="fa fa-trash"></i>
                    </a>
                </div>
                <div class="card-body">
                    <form method="post" id="formCadastro">
                        <div class="form-group row">
                            <div class="col-auto py-2">
                                <label for="placa">Placa:</label>
                                <input type="text" class="form-control" id="placa" name="placa"
                                       value="<?= $vehicle->getPlaca() ?>"
                                       required
                                       maxlength="7">
                            </div>
                            <div class="col-auto py-2">
                                <label for="renavam">Renavam:</label>
                                <input type="text" class="form-control" id="renavam" name="renavam"
                                       value="<?= $vehicle->getRenavam() ?>"
                                       maxlength="30">
                            </div>
                            <div class="col-auto py-2">
                                <label for="modelo">Modelo:</label>
                                <input type="text" class="form-control" id="modelo" name="modelo"
                                       value="<?= $vehicle->getModelo() ?>"
                                       required maxlength="20">
                            </div>
                            <div class="col-auto py-2">
                                <label for="marca">Marca:</label>
                                <input type="text" class="form-control" id="marca" name="marca"
                                       value="<?= $vehicle->getMarca() ?>" required
                                       maxlength="20">
                            </div>
                            <div class="col-auto py-2">
                                <label for="ano">Ano:</label>
                                <input type="number" class="form-control" id="ano" name="ano"
                                       value="<?= $vehicle->getAno() ?>" required>
                            </div>
                            <div class="col-auto py-2">
                                <label for="cor">Cor:</label>
                                <input type="text" class="form-control" id="cor" name="cor"
                                       value="<?= $vehicle->getCor() ?>" required
                                       maxlength="20">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success" id="saveButton" disabled>Salvar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
