<div class="container">
    <div class="row py-3">
        <div class="col-12 card">
            <h2 class="card-title text-center">Lista de Veículos</h2>
            <table class="table table-hover table-striped">
                <thead>
                <tr>
                    <th>Placa</th>
                    <th>Modelo</th>
                    <th>Marca</th>
                    <!-- Outros campos -->
                </tr>
                </thead>
                <tbody>
                <!--         Loop para exibir os veículos -->
                <?php foreach ($this->vehicles as $vehicle) : ?>
                    <tr>
                        <td><?= $vehicle->getPlaca(); ?></td>
                        <td><?= $vehicle->getModelo(); ?></td>
                        <td><?= $vehicle->getMarca(); ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
