<div class="container mt-5">
    <div class="text-center">
        <h1>SISTEMA DE GESTÃO DE FROTA</h1>
        <p class="lead">Escolha uma opção abaixo:</p>
    </div>

    <div class="row justify-content-center mt-4">
        <div class="col-md-4">
            <a href="/vehicles" class="btn btn-primary btn-block mb-3">
                <i class="fas fa-car fa-4x p-3"></i>
                <h3>Veículos</h3>
            </a>
        </div>
        <div class="col-md-4">
            <a href="/motorist" class="btn btn-success btn-block mb-3">
                <i class="fas fa-user fa-4x p-3"></i>
                <h3>Motoristas</h3>
            </a>
        </div>
        <div class="col-md-4">
            <a href="/map" class="btn btn-info btn-block">
                <i class="fas fa-map-marked-alt fa-4x p-3"></i>
                <h3>Mapa</h3>
            </a>
        </div>
    </div>
</div>
