<div class="container my-3">
    <div class="row">
        <div class="col-12">
            <a href="<?= $this->url('home') ?>" class="btn btn-primary mb-3">
                <i class="fa fa-arrow-left"></i> Voltar
            </a>
        </div>
    </div>
    <div class="row py-3">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h1>Localização de veículos</h1>
                </div>
                <div class="card-body">
                    <div id="map" style="height: 700px" class="w-100"></div>
<!--                    <iframe src="https://storage.googleapis.com/maps-solutions-51yr2cq6r0/locator-plus/s15d/locator-plus.html"-->
<!--                            width="100%" height="700px"-->
<!--                            style="border:0;"-->
<!--                            loading="lazy">-->
<!--                    </iframe>-->
                </div>
            </div>
        </div>
    </div>
</div>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD1DxZjwORvDrx4w3gAQyePW8AxhYxE6g8&callback=initMap"></script>

<script>
    function initMap() {
        // Coordenadas do centro do mapa
        const center = {lat: -25.390000, lng: -51.475532};

        // Inicializa o mapa
        const map = new google.maps.Map(document.getElementById('map'), {
            zoom: 6,
            center: center
        });

        // Lista de Marcadores
        const markers = [
            {
                position: {lat: -27.097231, lng: -52.614212},
                vehicle: 'ABC-1234',
                driver: 'João Silva'
            },
            {
                position: {lat: -23.5501, lng: -46.6346},
                vehicle: 'DEF-5678',
                driver: 'João Pedro'
            },
            {
                position: {lat: -25.451517, lng: -49.224018},
                vehicle: 'TEC-5050',
                driver: 'Marcelo Lira'
            },
            {
                position: {lat: -26.619568, lng: -54.107356},
                vehicle: 'AB 128 KJ',
                driver: 'Lionel Messi'
            }
        ];

        // <Marcadores ao mapa>
        markers.forEach(marker => {
            const newMarker = new google.maps.Marker({
                position: marker.position,
                map: map,
                title: marker.vehicle
            });

            // Cria InfoWindow
            const infoWindow = new google.maps.InfoWindow({
                content: `<div><h4>Veículo: ${marker.vehicle}</h4></div><div><h4>Motorista: ${marker.driver}</h4></div>`
            });

            // Adiciona evento de clique para exibir a InfoWindow
            newMarker.addListener('click', () => {
                infoWindow.open(map, newMarker);
            });
        });
    }
</script>
